# Generated by Django 3.1.7 on 2021-05-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://www.dealermarketing.com/wp-content/uploads/2014/04/k15679137-default-male-and-female-facebook-profile-image-785x505.jpg'),
        ),
    ]
