# Generated by Django 3.1.6 on 2021-02-17 05:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210215_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('HTML', 'HTML'), ('Freebies', 'Freebies'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('Tutorials', 'Tutorials')], default='....', max_length=155),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
