# Generated by Django 3.1.7 on 2021-05-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210217_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heading_image',
            field=models.URLField(),
        ),
    ]
